development: &development
  adapter: postgresql
  database: trackwane_development
  host: localhost
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_trackwane

test: &test
  <<: *development
  database: trackwane_test

production:
  <<: *development
  host: galileo.codeifier.com
  database: trackwane_production
  username: deployment
  password: FireDrake[1981]
