development: &development
  adapter: postgresql
  database: gowane_development
  host: localhost
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_gowane

test: &test
  <<: *development
  database: gowane_test

production:
  <<: *development
  host: galileo.codeifier.com
  database: gowane_production
  username: deployment
  password: FireDrake[1981]
  

cucumber:
  <<: *test